# App Info
spring.application.name=SwiftMartAPI
server.port=8089
server.address=0.0.0.0
org.gradle.internal.http.socketTimeout=60000
org.gradle.internal.http.connectionTimeout=60000

# PostgreSQL DB Config
spring.datasource.url=jdbc:postgresql://localhost:5432/SwiftMart
spring.datasource.username=postgres
spring.datasource.password=Thingabob
spring.datasource.initialization-mode=always
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=sameonshopgh@gmail.com
spring.mail.password=1953@Ahema
spring.mail.protocol=smtps

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.default-encoding=UTF-8


# DevTools (Optional)
spring.devtools.add-properties=false
#pbxplwlbodibmnpa

twilio.account.sid=ACd40d0d7eaaf6fe015435a7532b57566a
twilio.auth.token=d959c8357f230540aa61cbcb01af027f
twilio.phone.number=+233240655990
